### ISSUE TITLE
No Documents

### ISSUE THREAD

**Issue by baehyunsol** [StratusFearMe21/grezi#1]
I want to give it a try, but I don't know where to start.

**Comment by StratusFearMe21** [comment]
Yeah, I'm working on that. In the mean time you can look at the wiki https://github.com/StratusFearMe21/grezi/wiki/Syntax. It's 100% complete but I'm working on making it easier to understand.

**Comment by StratusFearMe21** [comment]
btw make sure you're using the latest version of grezi, as it implements breaking syntax changes that make it incompatible with the last version https://github.com/StratusFearMe21/grezi/releases/v2.1.0. It's also the version the wiki is based on
